#!/bin/bash

# uncomment the following line to skip the optional inlists
MESA_SKIP_OPTIONAL=t

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

# check if can skip building starting model
if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_tams.mod tams.mod
else
   do_one inlist_toTAMS_header tams.mod
   cp tams.mod standard_tams.mod
fi

do_one inlist_postTAMS_header tams.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished x'
